import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "bn";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string, variables?: Record<string, any>) => string;
}

const translations = {
    en: {
        home: "Home",
        findDonor: "Find Donor",
        emergencyRequests: "Emergency Requests",
        about: "About",
        contact: "Contact",
        login: "Login",
        joinAsDonor: "Join as Donor",
        signOut: "Sign Out",
        profile: "Profile",
        live: "Live",
        search: "Search",
        welcome: "👋 Welcome to BloodConnect!",
        welcomeMsg: "Register in 30 seconds. Save a life today. ❤️",
        // Hero
        heroTitle: "Someone near you needs blood",
        heroTitleHighlight: "in the next 2 hours.",
        heroSubtitle: "Join 50,000+ verified donors saving lives across Bangladesh. Every second counts.",
        findBloodNow: "Find Blood Now",
        // Impact Stats
        ourImpact: "Our Impact",
        realNumbers: "Real Numbers, Real Lives",
        statDesc: "Every statistic represents a life saved, a family reunited, a hope restored",
        activeDonors: "Active Donors",
        verifiedDonors: "Verified donors",
        livesSaved: "Lives Saved",
        hospitalConfirmed: "Hospital confirmed",
        districtsCovered: "Districts Covered",
        acrossBangladesh: "Across Bangladesh",
        successRate: "Success Rate",
        realtimeUpdated: "Real-time updated",
        govRegistered: "Government Registered",
        redCrescentPartner: "Red Crescent Partner",
        partnerHospitals: "50+ Partner Hospitals",
        // Smart Quick Search
        smartDonorSearch: "Smart Donor Search",
        findDonorsInstantly: "Find compatible donors near you instantly",
        emergency: "Emergency",
        normal: "Normal",
        hospitalName: "Hospital Name *",
        enterHospitalName: "Enter hospital name",
        divisionDistrict: "Division / District",
        selectArea: "Select area",
        useMyLocation: "Use My Location",
        detectingLocation: "Detecting...",
        donorsFound: "{count} donors found",
        matchingCriteria: "matching your criteria",
        searchingDonors: "Searching donors...",
        noDonorsFoundCriteria: "No donors found for this criteria",
        findBloodEmergency: "Find Blood Now - Emergency",
        searchDonorsBtn: "Search Donors",
        locationDetected: "Location detected: {location}",
        unableToDetectLocation: "Unable to detect location. Please select manually.",
        geolocationNotSupported: "Geolocation not supported by your browser",
        locationDetectionFailed: "Location detection failed",
        pleaseSelectBloodGroup: "Please select a blood group",
        // Why Donate
        whyDonateTitle: "Why Donate Blood?",
        everyDrop: "Every Drop Makes a Difference",
        everyDropDesc: "Discover how your simple act of kindness creates waves of hope and healing",
        saveLife: "Save a Life",
        saveLifeEmo: "Your one bag saved a child's life.",
        saveLifeMed: "One donation can save up to 3 lives",
        quickEasy: "Quick & Easy",
        quickEasyEmo: "30 minutes of your time, a lifetime for someone else.",
        quickEasyMed: "Simple process from registration to donation",
        freeCheckup: "Free Health Check",
        freeCheckupEmo: "Know your health while helping others.",
        freeCheckupMed: "Complete blood screening at no cost",
        healthBenefits: "Health Benefits",
        healthBenefitsEmo: "Your body regenerates healthier blood.",
        healthBenefitsMed: "Reduces risk of heart disease & maintains iron levels",
        // How it Works
        howItWorksTitle: "How It Works",
        simpleSteps: "Simple Steps to Save Lives",
        howItWorksDesc: "Our platform makes it incredibly easy to connect blood donors with those in need",
        readyToMakeDifference: "Ready to Make a Difference?",
        joinThousands: "Join thousands of donors saving lives every day",
        watchDemo: "Watch 60-sec Demo",
        getStarted: "Get Started",
        platformAvailability: "Platform availability",
        noHiddenCharges: "No hidden charges ever",
        step1Title: "Register",
        step1Desc: "Create your account in 30 seconds with basic info and phone verification.",
        step2Title: "Search or Request",
        step2Desc: "Find compatible donors nearby or post an urgent blood request instantly.",
        step3Title: "Connect with Donor",
        step3Desc: "Contact verified donors directly via call or WhatsApp. Fast and secure.",
        step4Title: "Save a Life",
        step4Desc: "Complete the donation and earn badges for your life-saving contribution.",
        // Testimonials
        realStories: "Real Stories",
        communitySays: "What Our Community Says",
        testimonialsDesc: "Real stories from verified donors and recipients who experienced the power of community",
        verifiedDonorBadge: "Verified Donor",
        verifiedPatientBadge: "Verified Patient",
        testimonial1Name: "Rahim Ahmed",
        testimonial1Role: "Regular Donor",
        testimonial1Quote: "Donating blood through BloodConnect has been incredibly easy. I've saved multiple lives and it feels amazing!",
        testimonial2Name: "Fatima Begum",
        testimonial2Role: "Emergency Recipient",
        testimonial2Quote: "When my father needed urgent blood, BloodConnect connected us with donors within hours. This platform is a lifesaver!",
        testimonial3Name: "Karim Hassan",
        testimonial3Role: "Monthly Donor",
        testimonial3Quote: "The process is seamless and the community is wonderful. I'm proud to be part of this life-saving network.",
        testimonial4Name: "Ayesha Rahman",
        testimonial4Role: "Mother & Recipient",
        testimonial4Quote: "My child urgently needed blood. Thanks to the wonderful donors found here, she's healthy again.",
        testimonial5Name: "Imran Hossain",
        testimonial5Role: "First-time Donor",
        testimonial5Quote: "Giving blood for the first time made me realize how easy it is to make a real difference in someone's life.",
        testimonial6Name: "Nasrin Akter",
        testimonial6Role: "Community Organizer",
        testimonial6Quote: "Our community drives with BloodConnect foster unity and kindness. It's wonderful to save lives together!",
        // First Visit Banner
        welcomeToBloodConnect: "Welcome to BloodConnect!",
        register30Sec: "Register in 30 seconds. Save a life today.",
        signup30Sec: "30 sec signup",
        joinNow: "Join Now",
        join: "Join",
        // Exit Intent Popup
        dontLeaveYet: "Don't Leave Yet",
        beforeYouLeave: "Before you leave —",
        someoneNearYou: "Someone near you might need your blood.",
        every2Seconds: "Every 2 seconds",
        bdEvery2Seconds: "someone in Bangladesh needs blood. Your registration could save a life today.",
        registerAsDonor: "Register as Donor",
        maybeLater: "Maybe Later",
        // Find Donors Page
        findBloodDonors: "Find Blood Donors",
        connectVerifiedDonors: "Connect with verified donors in your area",
        filters: "Filters",
        resetAllFilters: "Reset all filters",
        bloodGroup: "Blood Group",
        selectBloodGroup: "Select blood group",
        location: "Location",
        enterAreaDistrict: "Enter area/district",
        gender: "Gender",
        selectGender: "Select gender",
        any: "Any",
        lastDonation: "Last Donation",
        selectPeriod: "Select period",
        availability: "Availability",
        selectAvailability: "Select availability",
        distance: "Distance",
        distanceLabel: "Distance",
        selectDistance: "Select distance",
        urgentAvailability: "Urgent Availability",
        verifiedDonorsFilter: "Verified Donors",
        searchDonorsPlaceholder: "Search donors by name or location...",
        showingDonors: "Showing {count} donors",
        sortByDistance: "Sort by Distance",
        sortByRating: "Sort by Rating",
        sortByDonations: "Sort by Donations",
        sortByRecent: "Sort by Recent Activity",
        loadingDonors: "Loading donors...",
        failedToLoadDonors: "Failed to load donors:",
        noDonorsFound: "No donors found.",
        availableNow: "Available now",
        notAvailable: "Not available",
        lastDonationPrefix: "Last donation: ",
        noRecentDonation: "No recent donation info",
        viewProfile: "View Profile",
        loadMoreDonors: "Load More Donors",
        active: "Active",
        anonymousDonor: "Anonymous Donor",
        // Options
        male: "Male",
        female: "Female",
        other: "Other",
        within24hrs: "Within 24 hours",
        ago3months: "3+ months ago",
        ago6months: "6+ months ago",
        ago1year: "1+ year ago",
        within5km: "Within 5 km",
        within10km: "Within 10 km",
        within25km: "Within 25 km",
        within50km: "Within 50 km",
        // Generic Actions
        postRequest: "Post Request",
        // Trust & Security
        trustSecurity: "Trust & Security",
        safetyPriority: "Your Safety is Our Priority",
        trustDesc: "We employ multiple layers of verification to ensure every interaction on our platform is safe and genuine",
        phoneVerified: "Phone-Verified Donors",
        phoneVerifiedDesc: "Every donor's phone number is verified through OTP",
        fakeRequestsBanned: "Fake Requests Banned",
        fakeRequestsBannedDesc: "Fraudulent accounts are permanently banned",
        hospitalVerified: "Hospital Verified",
        hospitalVerifiedDesc: "Request locations verified by partner hospitals",
        dataEncrypted: "Data Encrypted",
        dataEncryptedDesc: "All personal data is encrypted and protected",
        trustedByCount: "Trusted by 50,000+ verified donors across Bangladesh",
        // Trusted Partners
        trustedPartners: "Trusted by leading partners",
        trustedPartnersDesc: "We collaborate with top organizations to save lives",
        // Urgent Requests
        urgentBloodRequests: "Urgent Blood Requests",
        fetchingRequests: "Fetching latest emergency blood requests...",
        troubleLoading: "Having trouble loading requests. Please try again.",
        retry: "Retry",
        allClear: "All Clear",
        noUrgentRequests: "No Urgent Requests Right Now",
        noUrgentRequestsDesc: "Good news! There are no urgent blood requests at the moment. Check back later or browse all requests.",
        viewAllRequests: "View All Requests",
        liveEmergencyRequests: "Live Emergency Requests",
        urgentRequestsDesc: "These patients need blood donations immediately. Your quick response can save a life.",
        bloodNeeded: "Blood Needed",
        unitsRequired: "units required",
        posted: "Posted",
        callNow: "Call Now",
        minAgo: "min ago",
        hAgo: "h ago",
        dAgo: "days ago", // Modified
        // Time Ago with variables
        secondsAgo: "{count} seconds ago",
        minutesAgo: "{count} minutes ago",
        hoursAgo: "{count} hours ago",
        daysAgo: "{count} days ago",
        // Urgency
        immediate: "Immediate",
        urgent: "Urgent",
        flexible: "Flexible",
        immediateDesc: "Critical - needed within hours",
        urgentDesc: "Needed within 24 hours",
        flexibleDesc: "Can wait a few days",
        // Footer & Generic
        needBloodUrgently: "Need blood urgently?",
        postEmergencyRequest: "Post Emergency Request",
        whatsApp: "WhatsApp",
        footerMission: "Bangladesh's trusted blood donation platform. Connecting verified donors with patients in need, 24/7.",
        partnerHospitalsTitle: "Partner Hospitals",
        morePartners: "+ 50 more partners",
        hotline: "Hotline",
        support247: "24/7 Support",
        privacyPolicy: "Privacy Policy",
        termsOfService: "Terms of Service",
        madeWith: "Made with",
        forBangladesh: "for Bangladesh",
        allRightsReserved: "All rights reserved.",
        links: "Quick Links",
        newsletter: "Join Newsletter",
        subscribe: "Subscribe",
        // Request Blood Page
        bloodRequests: "Blood Requests",
        bloodRequestsDesc: "Find and respond to urgent blood needs in your community",
        createRequest: "Create Request",
        loginToRequest: "Login to Request",
        clearFilters: "Clear Filters",
        groupFilter: "Group: {group}",
        urgencyFilter: "Urgency: {urgency}",
        searchFilter: "Search: \"{query}\"",
        locationPatientPlaceholder: "Location, patient info...",
        urgency: "Urgency",
        // Create Request Page
        backToBloodRequests: "Back to Blood Requests",
        bloodRequestDetails: "Blood Request Details",
        bloodRequestDetailsDesc: "Please provide accurate information to help us find the right donors for you.",
        patientInformation: "Patient Information",
        patientInfoLabel: "Patient Information *",
        patientInfoPlaceholder: "Enter patient's name or condition",
        unitsNeededLabel: "Units Needed *",
        unitsNeededPlaceholder: "Number of units",
        bloodGroupRequired: "Blood Group Required *",
        urgencyLevel: "Urgency Level",
        locationInformation: "Location Information",
        hospitalLocationLabel: "Hospital/Location *",
        hospitalLocationPlaceholder: "Enter hospital name or location",
        phoneNumberLabel: "Phone Number *",
        submitBloodRequest: "Submit Blood Request",
        requestSubmitted: "Request Submitted",
        requestSubmittedDesc: "Your blood request has been submitted successfully.",
        requestFailed: "Request Failed",
        requestFailedDesc: "Failed to submit blood request. Please try again.",
        // Profile Page
        loading: "Loading...",
        notSet: "Not set",
        recently: "Recently",
        newDonor: "New Donor",
        totalDonations: "Total Donations",
        livesImpacted: "Lives Impacted",
        achievements: "Achievements",
        overview: "Overview",
        history: "History",
        requests: "Requests",
        donationStatus: "Donation Status",
        nextEligible: "Next Eligible:",
        status: "Status:",
        updateAvailability: "Update Availability",
        notificationSettings: "Notification Settings",
        donationHistory: "Donation History",
        noDonationHistory: "No donation history yet.",
        yourAchievements: "Your Achievements",
        matchingRequests: "Matching Blood Requests",
        matchingRequestsDesc: "Urgent requests matching your blood group",
        noMatchingRequests: "No matching requests found.",
        respond: "Respond",
        joinedPrefix: "Joined ",
        editProfile: "Edit Profile",
        // Achievement Titles & Descriptions
        bronzeDonor: "Bronze Donor",
        bronzeDesc: "5 successful donations",
        silverDonor: "Silver Donor",
        silverDesc: "10 successful donations",
        goldDonor: "Gold Donor",
        goldDesc: "15 successful donations",
        platinumDonor: "Platinum Donor",
        platinumDesc: "25 successful donations",
        lifeSaver: "Life Saver",
        lifeSaverDesc: "50 successful donations",
        // Time Ago
        // These were moved to be with other time ago keys
        // secondsAgo: "{count} seconds ago",
        // minutesAgo: "{count} minutes ago",
        // hoursAgo: "{count} hours ago",
        // daysAgo: "{count} days ago",
        // Auth Pages (Sign In / Sign Up)
        welcomeBack: "Welcome Back",
        signInDesc: "Sign in to your account",
        email: "Email",
        password: "Password",
        forgotPassword: "Forgot password?",
        emailPlaceholder: "Enter your email",
        passwordPlaceholder: "Enter your password",
        signingIn: "Signing In...",
        signIn: "Sign In",
        or: "Or",
        continueWithGoogle: "Continue with Google",
        needAccount: "Need a new account?",
        signUp: "Sign Up",
        alreadyHaveAccount: "Already have an account?",
        resetPassword: "Reset Password",
        resetPasswordDesc: "Enter your email address and we'll send you a link to reset your password.",
        sending: "Sending...",
        sendResetLink: "Send Reset Link",
        // Toast Messages
        success: "Success",
        signedInSuccess: "Signed in successfully!",
        signInFailed: "Sign In Failed",
        unexpectedError: "An unexpected error occurred. Please try again.",
        incorrectPassword: "Incorrect Password",
        incorrectPasswordDesc: "The password you entered is incorrect. Please try again or reset your password.",
        accountNotFound: "Account Not Found",
        accountNotFoundDesc: "No account exists with this email. Please check your email or sign up.",
        emailNotVerified: "Email Not Verified",
        emailNotVerifiedDesc: "Please check your inbox and verify your email before signing in.",
        tooManyAttempts: "Too Many Attempts",
        tooManyAttemptsDesc: "You've made too many login attempts. Please wait a few minutes and try again.",
        checkYourEmail: "Check your email",
        resetEmailSent: "If an account exists with this email, you will receive a password reset link.",
        errorTitle: "Error",
        googleSignInFailed: "Failed to sign in with Google",
        // Sign Up
        createNewAccount: "Create New Account",
        joinService: "Join the blood donation service",
        fullName: "Full Name",
        fullNamePlaceholder: "Enter your full name",
        phoneLabel: "Phone Number",
        phoneNote: "Note: You cannot change your phone number after registration.",
        nidLabel: "National ID Number",
        nidPlaceholder: "Enter your NID number",
        passwordStrongPlaceholder: "Enter a strong password",
        confirmPassword: "Confirm Password",
        confirmPasswordPlaceholder: "Re-enter your password",
        creatingAccount: "Creating Account...",
        createAccount: "Create Account",
        passwordsDoNotMatch: "Passwords do not match",
        accountCreatedSuccess: "Account created successfully! Please check your email to confirm your address.",
        notice: "Notice",
        profileIssueNotice: "Account created successfully! Profile creation had an issue but your account is still active. You can complete your profile later.",
        dbSetupRequired: "Database Setup Required",
        dbSetupDesc: "The user_profiles table doesn't exist in the database. Please run the SQL script from create-user-profiles-table.sql in your Supabase SQL editor.",
        signUpFailed: "Failed to create account",
        // Complete Profile
        completeYourProfile: "Complete Your Profile",
        completeProfileDesc: "Please provide the following information to complete your registration",
        district: "District",
        districtPlaceholder: "e.g., Dhaka",
        nationalId: "National ID",
        saving: "Saving...",
        validationError: "Validation Error",
        checkInput: "Please check your input",
        profileCompletedSuccess: "Profile completed successfully!",
        profileUpdateFailed: "Failed to update profile",
        // Donor Registration Dialog
        donorRegistration: "Donor Registration",
        personalInfo: "Personal Info",
        healthScreening: "Health Screening",
        termsPrivacy: "Terms & Privacy",
        basicDetails: "Basic Details",
        medicalHistory: "Medical History",
        legalAgreement: "Legal Agreement",
        personalInfoDesc: "Provide your personal information and contact details",
        healthScreeningDesc: "Complete health questionnaire (for donors only)",
        termsPrivacyDesc: "Review and accept our terms of service and privacy policy",
        healthScreeningRequired: "Health Screening Required",
        healthScreeningNote: "Please answer all questions honestly. This information helps ensure safe blood donation for both donors and recipients.",
        weightPlaceholder: "Select weight",
        heightPlaceholder: "170",
        minWeightNote: "Minimum 50kg required",
        lastDonationDate: "Last Donation Date",
        dateOfBirth: "Date of Birth",
        firstTimeDonor: "First Time?",
        mustBe18to60: "Must be 18-60 years old",
        otherMedicalConditions: "Other Medical Conditions",
        lifestyleMedications: "Lifestyle & Medications",
        recentActivities: "Recent Activities",
        recentActivitiesNote: "In the past 3 months, have you:",
        medicalHistoryNote: "Do you currently have or have you ever been diagnosed with any of the following conditions?",
        otherConditionsPlaceholder: "Please specify any other conditions",
        confirmAccuracy: "I confirm that all the information provided above is accurate and complete",
        termsOfServiceAgree: "I agree to the Terms of Service",
        privacyPolicyAgree: "I agree to the Privacy Policy",
        notificationConsent: "I consent to receive SMS and email notifications about urgent blood requests",
        notificationConsentNote: "You can change this preference later in your profile settings",
        profileSharingConsent: "I consent to sharing my profile information with verified recipients when there's a blood type match",
        profileSharingConsentNote: "This is essential for the platform to function and connect donors with recipients",
        privacyMatters: "Your Privacy Matters",
        privacyMattersNote: "We are committed to protecting your personal information and medical data. Your information is encrypted and only shared with your explicit consent for blood matching purposes.",
        secureRegistration: "Secure Registration",
        registering: "Registering...",
        completeRegistration: "Complete Registration",
        registrationSuccess: "Registration Successful!",
        registrationSuccessNote: "Thank you for becoming a donor. Your commitment helps save lives.",
        done: "Done",
        missingInfo: "Missing Information",
        fillRequiredFields: "Please fill in all required fields marked with *",
        invalidEmail: "Invalid Email",
        enterValidEmail: "Please enter a valid email address",
        invalidPhone: "Invalid Phone Number",
        enterValidPhone: "Please enter a valid Bangladeshi phone number",
        enterWeightHeight: "Please enter your weight and height",
        provideLastDonationDate: "Please provide your last donation date or indicate if you are a first-time donor",
        confirmationRequired: "Confirmation Required",
        confirmInfoAccurate: "Please confirm that the information provided is accurate",
        agreementsRequired: "Agreements Required",
        acceptAgreements: "Please accept the Terms of Service, Privacy Policy, and Profile Sharing consent",
        registrationFailed: "Registration Failed",
        division: "Division",
        divisionPlaceholder: "Select your division",
        fullAddress: "Full Address",
        fullAddressPlaceholder: "House/Road/Area details",
        recipientsFindYou: "This helps nearby recipients find you",
        activePhoneNote: "Note: Please ensure this is Your active phone number.",
        // Medical conditions
        heartDisease: "Heart disease or heart problems",
        diabetes: "Diabetes",
        hepatitis: "Hepatitis B or C",
        tuberculosis: "Tuberculosis",
        liverDisease: "Liver disease",
        highLowBloodPressure: "High or low blood pressure",
        cancerBloodDisorders: "Cancer or blood disorders",
        hivAids: "HIV/AIDS",
        kidneyDisease: "Kidney disease",
        epilepsySeizures: "Epilepsy or seizures",
        // Lifestyle
        prescriptionMedications: "I am currently taking prescription medications",
        smokeTobacco: "I smoke tobacco products",
        consumeAlcohol: "I consume alcohol regularly",
        // Recent activities
        vaccinations: "Had any vaccinations or immunizations",
        dentalWork: "Had any dental work or surgery",
        traveledOutside: "Traveled outside Bangladesh",
        tattoosPiercings: "Had any tattoos or piercings",
        beenSick: "Been sick with fever, cold, or flu",
        weight: "Weight",
        height: "Height (cm)",
        previous: "Previous",
        next: "Next",
        // About Page
        aboutTitle: "About BloodConnect",
        aboutMission: "BloodConnect is a platform dedicated to connecting blood donors with recipients across Bangladesh. Our mission is to reduce the time to find compatible donors, streamline urgent requests, and build a dependable, community-driven network that saves lives every day.",
        whatWeDo: "What we do",
        whatWeDoDesc: "We aggregate donor availability, match urgent requests, and notify potential donors in real-time.",
        whyItMatters: "Why it matters",
        whyItMattersDesc: "Timely access to blood can be life-saving. We help reduce friction, delay, and uncertainty.",
        forOurUsers: "For our users",
        forOurUsersDesc: "Donors gain a simple way to contribute. Recipients get a reliable path to urgent help.",
        privacyPolicyTitle: "Privacy Policy",
        privacyPolicyDesc: "We collect essential information to operate the platform—such as account details and donor preferences. Your data is stored securely and accessed only for service functionality, safety, and compliance. We never sell your personal data. You may request data export or deletion in accordance with applicable laws.",
        faqTitle: "Frequently Asked Questions",
        faqQ1: "How do I become a donor?",
        faqA1: "Create an account and complete your donor profile with blood group and availability. You can update preferences anytime.",
        faqQ2: "Is my personal information safe?",
        faqA2: "Yes. We use secure storage and restrict access to operational needs. See our Privacy Policy for details.",
        faqQ3: "Do you charge any fees?",
        faqA3: "No. BloodConnect is free for donors and recipients. We may add optional features in the future with clear disclosure.",
        faqQ4: "How are matches made?",
        faqA4: "We match based on blood group compatibility, proximity, and donor availability to maximize response speed and safety.",

        // Contact Page
        contactTitle: "Get in Touch",
        contactSubtitle: "Have questions or need assistance? We're here to help you save lives. Reach out to us anytime.",
        emergencyHotline: "Emergency Hotline",
        hotlineHours: "24/7 available for urgent blood needs",
        emailUs: "Email Us",
        emailResponse: "We'll respond within 24 hours",
        headOffice: "Head Office",
        headOfficeLocation: "Dhaka, Bangladesh",
        officeHours: "Office Hours",
        officeHoursDesc: "Sun - Thu: 9AM - 6PM",
        officeHoursClosed: "Closed on public holidays",
        telephoneEnquiries: "Blood Donor Telephone Enquiries",
        hotlineNumber: "0345 90 90 999",
        monFri: "Monday - Friday: 9:00 AM - 5:00 PM",
        callUsIfTitle: "Give us a ring if you:",
        ringSignUps: "Want to sign up as a blood donor",
        ringSignUpsDesc: "Register to become a life-saving donor",
        ringQuestions: "Have questions about giving blood",
        ringQuestionsDesc: "Get answers to your donation queries",
        ringAppointment: "Make or cancel an appointment",
        ringAppointmentDesc: "Until 5pm the day before the session",
        ringMedical: "Need medical advice",
        ringMedicalDesc: "Consult with our medical team",
        ringUnwell: "Feel unwell after giving blood",
        ringUnwellDesc: "Medical team on-call 24 hours",
        ringDiscomfort: "Suffer discomfort after donation",
        ringDiscomfortDesc: "Medical team on-call 24 hours",
        ringUsage: "Have doubts about blood usage",
        ringUsageDesc: "Concerns after donation",
        importantNote: "Note:",
        medicalEmergencyNote: "For medical emergencies after donation, our medical team is available 24/7. Don't hesitate to call if you experience any discomfort or concerns.",
        sendMessage: "Send us a Message",
        sendMessageDesc: "Fill out the form below and we'll get back to you as soon as possible.",
        fullContactName: "Full Name *",
        enterFullName: "Enter your full name",
        emailAddressLabel: "Email Address *",
        phoneOptional: "Phone Number (Optional)",
        subjectLabel: "Subject *",
        regardingSubject: "What is this regarding?",
        messageLabel: "Message *",
        tellMoreMessage: "Tell us more about your inquiry...",
        characters: "characters",
        sendingMessage: "Sending Message...",
        responseTimeNote: "Response Time:",
        typicallyRespond: "We typically respond to all inquiries within 24 hours during business days.",
        needSomethingElse: "Need Something Else?",
        quickAccessFeatures: "Quick access to our most popular features",
        invalidName: "Name must be at least 2 characters",
        invalidSubject: "Subject must be at least 5 characters",
        invalidMessage: "Message must be at least 10 characters",

        // Blood Request Feed & Cards
        patient: "Patient",
        contactPerson: "Contact Person",
        unitsNeeded: "{units} unit(s) needed",
        share: "Share",
        iCanHelp: "I Can Help",
        noRequestsFound: "No blood requests found.",
        noMatchFound: "No blood requests match \"{query}\"",
        loadingRequests: "Loading blood requests...",
        messageSent: "Message Sent!",
        messageSentDesc: "Thank you for contacting us. We'll get back to you soon.",
    },
    bn: {
        home: "হোম",
        findDonor: "রক্তদাতা খুঁজুন",
        emergencyRequests: "জরুরি রক্ত অনুরোধ",
        about: "আমাদের সম্পর্কে",
        contact: "যোগাযোগ",
        login: "লগইন",
        joinAsDonor: "রক্তদাতা হিসেবে যুক্ত হোন",
        signOut: "লগ আউট",
        profile: "প্রোফাইল",
        live: "লাইভ",
        search: "অনুসন্ধান",
        welcome: "👋 ব্লাডকানেক্ট-এ স্বাগতম!",
        welcomeMsg: "৩০ সেকেন্ডে নিবন্ধন করুন। আজই প্রাণ বাঁচান। ❤️",
        // Hero
        heroTitle: "আপনার কাছের কারো রক্ত প্রয়োজন",
        heroTitleHighlight: "আগামী ২ ঘণ্টার মধ্যে।",
        heroSubtitle: "বাংলাদেশজুড়ে জীবন বাঁচানো ৫০,০০০+ যাচাইকৃত রক্তদাতার সাথে যুক্ত হোন। প্রতিটি সেকেন্ড মূল্যবান।",
        findBloodNow: "এখনই রক্ত খুঁজুন",
        // Impact Stats
        ourImpact: "আমাদের প্রভাব",
        realNumbers: "বাস্তব সংখ্যা, বাস্তব জীবন",
        statDesc: "প্রতিটি পরিসংখ্যান একটি জীবন বাঁচানো, একটি পরিবারের পুনর্মিলন এবং একটি আশা পুনরুদ্ধারের প্রতিনিধিত্ব করে",
        activeDonors: "সক্রিয় রক্তদাতা",
        verifiedDonors: "যাচাইকৃত রক্তদাতা",
        livesSaved: "জীবন বাঁচানো হয়েছে",
        hospitalConfirmed: "হাসপাতাল দ্বারা নিশ্চিত",
        districtsCovered: "জেলা কভার করা হয়েছে",
        acrossBangladesh: "বাংলাদেশজুড়ে",
        successRate: "সফলতার হার",
        realtimeUpdated: "রিয়েল-টাইমে আপডেট করা",
        govRegistered: "সরকার নিবন্ধিত",
        redCrescentPartner: "রেড ক্রিসেন্ট পার্টনার",
        partnerHospitals: "৫০+ পার্টনার হাসপাতাল",
        // Why Donate
        whyDonateTitle: "কেন রক্ত দেবেন?",
        everyDrop: "প্রতিটি বিন্দু পরিবর্তন আনে",
        everyDropDesc: "জানুন কীভাবে আপনার সাধারণ দয়ার কাজ আশা ও সুস্থতার ঢেউ তৈরি করে",
        saveLife: "জীবন বাঁচান",
        saveLifeEmo: "আপনার এক ব্যাগ রক্ত একটি শিশুর জীবন বাঁচিয়েছে।",
        saveLifeMed: "একবার রক্তদানে ৩টি জীবন বাঁচানো যায়",
        quickEasy: "দ্রুত ও সহজ",
        quickEasyEmo: "আপনার ৩০ মিনিট সময়, অন্য কারো জন্য আজীবন।",
        quickEasyMed: "নিবন্ধন থেকে রক্তদান পর্যন্ত সহজ প্রক্রিয়া",
        freeCheckup: "বিনামূল্যে স্বাস্থ্য পরীক্ষা",
        freeCheckupEmo: "অন্যকে সাহায্য করার পাশাপাশি আপনার স্বাস্থ্য সম্পর্কে জানুন।",
        freeCheckupMed: "বিনা খরচে সম্পূর্ণ রক্ত পরীক্ষা",
        healthBenefits: "স্বাস্থ্য সুবিধা",
        healthBenefitsEmo: "আপনার শরীর স্বাস্থ্যকর রক্ত পুনরুৎপাদন করে।",
        healthBenefitsMed: "হৃদরোগের ঝুঁকি কমায় এবং আয়রনের মাত্রা বজায় রাখে",
        // How it Works
        howItWorksTitle: "কীভাবে কাজ করে",
        simpleSteps: "জীবন বাঁচানোর সহজ ধাপ",
        howItWorksDesc: "আমাদের প্ল্যাটফর্ম রক্তদাতা এবং যাদের প্রয়োজন তাদের মধ্যে সংযোগ স্থাপন করা অবিশ্বাস্যভাবে সহজ করে তোলে",
        readyToMakeDifference: "পরিবর্তন আনতে প্রস্তুত?",
        joinThousands: "প্রতিদিন জীবন বাঁচানো হাজার হাজার রক্তদাতার সাথে যুক্ত হোন",
        // Smart Quick Search
        smartDonorSearch: "স্মার্ট রক্তদাতা অনুসন্ধান",
        findDonorsInstantly: "আপনার কাছের উপযুক্ত রক্তদাতাদের সাথে সাথে খুঁজুন",
        emergency: "জরুরি",
        normal: "সাধারণ",
        hospitalName: "হাসপাতালের নাম *",
        enterHospitalName: "হাসপাতালের নাম লিখুন",
        divisionDistrict: "বিভাগ / জেলা",
        selectArea: "এলাকা নির্বাচন করুন",
        useMyLocation: "আমার অবস্থান ব্যবহার করুন",
        detectingLocation: "খুঁজছি...",
        donorsFound: "{count} জন রক্তদাতা পাওয়া গেছে",
        matchingCriteria: "আপনার শর্তাবলীর সাথে মিলছে",
        searchingDonors: "রক্তদাতা খুঁজছি...",
        noDonorsFoundCriteria: "এই শর্তাবলীর সাথে কোনো রক্তদাতা পাওয়া যায়নি",
        findBloodEmergency: "এখনই রক্ত খুঁজুন - জরুরি",
        searchDonorsBtn: "রক্তদাতা অনুসন্ধান",
        locationDetected: "অবস্থান পাওয়া গেছে: {location}",
        unableToDetectLocation: "অবস্থান শনাক্ত করা সম্ভব হয়নি। অনুগ্রহ করে ম্যানুয়ালি নির্বাচন করুন।",
        geolocationNotSupported: "আপনার ব্রাউজারে জিওলোকেশন সমর্থিত নয়",
        locationDetectionFailed: "অবস্থান শনাক্তকরণ ব্যর্থ হয়েছে",
        pleaseSelectBloodGroup: "অনুগ্রহ করে রক্তের গ্রুপ নির্বাচন করুন",
        // Options
        male: "পুরুষ",
        female: "মহিলা",
        other: "অন্যান্য",
        within24hrs: "২৪ ঘণ্টার মধ্যে",
        ago3months: "৩+ মাস আগে",
        ago6months: "৬+ মাস আগে",
        ago1year: "১+ বছর আগে",
        within5km: "৫ কিমি এর মধ্যে",
        within10km: "১০ কিমি এর মধ্যে",
        within25km: "২৫ কিমি এর মধ্যে",
        within50km: "৫০ কিমি এর মধ্যে",
        // Urgency
        immediate: "তাত্ক্ষণিক",
        urgent: "জরুরি",
        flexible: "নমনীয়",
        immediateDesc: "তাত্ক্ষণিক - কয়েক ঘণ্টার মধ্যে প্রয়োজন",
        urgentDesc: "২৪ ঘণ্টার মধ্যে প্রয়োজন",
        flexibleDesc: "কয়েক দিন অপেক্ষা করতে পারে",
        // Request Blood Page
        bloodRequests: "রক্তের অনুরোধ",
        bloodRequestsDesc: "আপনার এলাকার জরুরি রক্তের প্রয়োজন খুঁজুন এবং সাড়া দিন",
        createRequest: "অনুরোধ তৈরি করুন",
        loginToRequest: "অনুরোধের জন্য লগইন করুন",
        clearFilters: "ফিল্টার মুছুন",
        groupFilter: "গ্রুপ: {group}",
        urgencyFilter: "জরুরি অবস্থা: {urgency}",
        searchFilter: "অনুসন্ধান: \"{query}\"",
        locationPatientPlaceholder: "অবস্থান, রোগীর তথ্য...",
        urgency: "জরুরি অবস্থা",
        // Create Request Page
        backToBloodRequests: "রক্তের অনুরোধে ফিরে যান",
        bloodRequestDetails: "রক্তের অনুরোধের বিবরণ",
        bloodRequestDetailsDesc: "আপনার জন্য সঠিক রক্তদাতা খুঁজে পেতে সাহায্য করার জন্য অনুগ্রহ করে সঠিক তথ্য প্রদান করুন।",
        patientInformation: "রোগীর তথ্য",
        patientInfoLabel: "রোগীর তথ্য *",
        patientInfoPlaceholder: "রোগীর নাম বা শারীরিক অবস্থা লিখুন",
        unitsNeededLabel: "প্রয়োজনীয় ইউনিট *",
        unitsNeededPlaceholder: "ইউনিটের সংখ্যা",
        bloodGroupRequired: "প্রয়োজনীয় রক্তের গ্রুপ *",
        urgencyLevel: "জরুরি অবস্থা",
        locationInformation: "অবস্থানের তথ্য",
        hospitalLocationLabel: "হাসপাতাল/অবস্থান *",
        hospitalLocationPlaceholder: "হাসপাতালের নাম বা অবস্থান লিখুন",
        phoneNumberLabel: "ফোন নম্বর *",
        submitBloodRequest: "রক্তের অনুরোধ জমা দিন",
        requestSubmitted: "অনুরোধ জমা দেওয়া হয়েছে",
        requestSubmittedDesc: "আপনার রক্তের অনুরোধ সফলভাবে জমা দেওয়া হয়েছে।",
        requestFailed: "অনুরোধ ব্যর্থ হয়েছে",
        requestFailedDesc: "রক্তের অনুরোধ জমা দিতে ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
        // Profile Page
        loading: "লোড হচ্ছে...",
        notSet: "সেট করা নেই",
        recently: "সম্প্রতি",
        availableNow: "এখনই পাওয়া যাবে",
        newDonor: "নতুন রক্তদাতা",
        totalDonations: "মোট রক্তদান",
        livesImpacted: "জীবন প্রভাবিত হয়েছে",
        achievements: "অর্জনসমূহ",
        overview: "এক নজরে",
        history: "ইতিহাস",
        requests: "অনুরোধসমূহ",
        donationStatus: "রক্তদানের অবস্থা",
        nextEligible: "পরবর্তী যোগ্যতার তারিখ:",
        status: "অবস্থা:",
        updateAvailability: "প্রাপ্যতা আপডেট করুন",
        notificationSettings: "নোটিফিকেশন সেটিংস",
        donationHistory: "রক্তদানের ইতিহাস",
        noDonationHistory: "এখনো কোনো রক্তদানের ইতিহাস নেই।",
        yourAchievements: "আপনার অর্জনসমূহ",
        matchingRequests: "মানানসই রক্তের অনুরোধ",
        matchingRequestsDesc: "আপনার রক্তের গ্রুপের সাথে মানানসই জরুরি অনুরোধ",
        noMatchingRequests: "কোনো মানানসই অনুরোধ পাওয়া যায়নি।",
        respond: "সাড়া দিন",
        joinedPrefix: "যুক্ত হয়েছেন ",
        editProfile: "প্রোফাইল এডিট করুন",
        // Achievement Titles & Descriptions
        bronzeDonor: "ব্রোঞ্জ রক্তদাতা",
        bronzeDesc: "৫টি সফল রক্তদান",
        silverDonor: "সিলভার রক্তদাতা",
        silverDesc: "১০টি সফল রক্তদান",
        goldDonor: "গোল্ড রক্তদাতা",
        goldDesc: "১৫টি সফল রক্তদান",
        platinumDonor: "প্ল্যাটিনাম রক্তদাতা",
        platinumDesc: "২৫টি সফল রক্তদান",
        lifeSaver: "লাইফ সেভার",
        lifeSaverDesc: "৫০টি সফল রক্তদান",
        // Time Ago
        // These were moved to be with other time ago keys
        // secondsAgo: "{count} সেকেন্ড আগে",
        // minutesAgo: "{count} মিনিট আগে",
        // hoursAgo: "{count} ঘণ্টা আগে",
        // daysAgo: "{count} দিন আগে",
        // Auth Pages (Sign In / Sign Up)
        welcomeBack: "স্বাগতম",
        signInDesc: "আপনার অ্যাকাউন্টে লগইন করুন",
        email: "ইমেইল",
        password: "পাসওয়ার্ড",
        forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
        emailPlaceholder: "আপনার ইমেইল লিখুন",
        passwordPlaceholder: "আপনার পাসওয়ার্ড লিখুন",
        signingIn: "লগইন হচ্ছে...",
        signIn: "লগইন",
        or: "অথবা",
        continueWithGoogle: "গুগল দিয়ে চালিয়ে যান",
        needAccount: "নতুন অ্যাকাউন্ট প্রয়োজন?",
        signUp: "নিবন্ধন করুন",
        alreadyHaveAccount: "ইতিমধ্যে একটি অ্যাকাউন্ট আছে?",
        resetPassword: "পাসওয়ার্ড রিসেট করুন",
        resetPasswordDesc: "আপনার ইমেইল ঠিকানা লিখুন এবং আমরা আপনাকে পাসওয়ার্ড রিসেট করার একটি লিঙ্ক পাঠাব।",
        sending: "পাঠানো হচ্ছে...",
        sendResetLink: "রিসেট লিঙ্ক পাঠান",
        // Toast Messages
        success: "সফল",
        signedInSuccess: "সফলভাবে লগইন করা হয়েছে!",
        signInFailed: "লগইন ব্যর্থ হয়েছে",
        unexpectedError: "একটি অপ্রত্যাশিত ত্রুটি ঘটেছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
        incorrectPassword: "ভুল পাসওয়ার্ড",
        incorrectPasswordDesc: "আপনার দেওয়া পাসওয়ার্ডটি ভুল। অনুগ্রহ করে আবার চেষ্টা করুন অথবা আপনার পাসওয়ার্ড রিসেট করুন।",
        accountNotFound: "অ্যাকাউন্ট পাওয়া যায়নি",
        accountNotFoundDesc: "এই ইমেইল দিয়ে কোনো অ্যাকাউন্ট নেই। অনুগ্রহ করে আপনার ইমেইল চেক করুন অথবা নিবন্ধন করুন।",
        emailNotVerified: "ইমেইল যাচাই করা হয়নি",
        emailNotVerifiedDesc: "লগইন করার আগে অনুগ্রহ করে আপনার ইনবক্স চেক করুন এবং আপনার ইমেইল যাচাই করুন।",
        tooManyAttempts: "অনেক বেশি প্রচেষ্টা",
        tooManyAttemptsDesc: "আপনি অনেক বার লগইন করার চেষ্টা করেছেন। অনুগ্রহ করে কয়েক মিনিট অপেক্ষা করুন এবং আবার চেষ্টা করুন।",
        checkYourEmail: "আপনার ইমেইল চেক করুন",
        resetEmailSent: "যদি এই ইমেইল দিয়ে কোনো অ্যাকাউন্ট থাকে, তবে আপনি একটি পাসওয়ার্ড রিসেট লিঙ্ক পাবেন।",
        errorTitle: "ত্রুটি",
        googleSignInFailed: "গুগল দিয়ে লগইন করতে ব্যর্থ হয়েছে",
        // Sign Up
        createNewAccount: "নতুন অ্যাকাউন্ট তৈরি করুন",
        joinService: "রক্তদান সেবার সাথে যুক্ত হোন",
        fullName: "পুরো নাম",
        fullNamePlaceholder: "আপনার পুরো নাম লিখুন",
        phoneLabel: "ফোন নম্বর",
        phoneNote: "নোট: নিবন্ধনের পরে আপনি আপনার ফোন নম্বর পরিবর্তন করতে পারবেন না।",
        nidLabel: "জাতীয় পরিচয়পত্র নম্বর",
        nidPlaceholder: "আপনার এনআইডি নম্বর লিখুন",
        passwordStrongPlaceholder: "একটি শক্তিশালী পাসওয়ার্ড লিখুন",
        confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
        confirmPasswordPlaceholder: "আপনার পাসওয়ার্ডটি আবার লিখুন",
        creatingAccount: "অ্যাকাউন্ট তৈরি হচ্ছে...",
        createAccount: "অ্যাকাউন্ট তৈরি করুন",
        passwordsDoNotMatch: "পাসওয়ার্ড মেলেনি",
        accountCreatedSuccess: "অ্যাকাউন্ট সফলভাবে তৈরি করা হয়েছে! আপনার ইমেইল ঠিকানা নিশ্চিত করতে অনুগ্রহ করে আপনার ইমেইল চেক করুন।",
        notice: "বিজ্ঞপ্তি",
        profileIssueNotice: "অ্যাকাউন্ট সফলভাবে তৈরি করা হয়েছে! প্রোফাইল তৈরিতে কিছু সমস্যা হয়েছে তবে আপনার অ্যাকাউন্ট এখনও সক্রিয়। আপনি পরে আপনার প্রোফাইলটি সম্পূর্ণ করতে পারেন।",
        dbSetupRequired: "ডেটাবেস সেটআপ প্রয়োজন",
        dbSetupDesc: "ডেটাবেসে user_profiles টেবিলটি নেই। অনুগ্রহ করে আপনার সুপাবেস এসকিউএল এডিটর থেকে create-user-profiles-table.sql স্ক্রিপ্টটি চালান।",
        signUpFailed: "অ্যাকাউন্ট তৈরি করতে ব্যর্থ হয়েছে",
        // Complete Profile
        completeYourProfile: "আপনার প্রোফাইল সম্পূর্ণ করুন",
        completeProfileDesc: "আপনার নিবন্ধন সম্পূর্ণ করতে অনুগ্রহ করে নিম্নলিখিত তথ্য প্রদান করুন",
        district: "জেলা",
        districtPlaceholder: "যেমন: ঢাকা",
        nationalId: "জাতীয় পরিচয়পত্র",
        saving: "সংরক্ষণ হচ্ছে...",
        validationError: "যাচাইকরণ ত্রুটি",
        checkInput: "অনুগ্রহ করে আপনার ইনপুট চেক করুন",
        profileCompletedSuccess: "প্রোফাইল সফলভাবে সম্পন্ন হয়েছে!",
        profileUpdateFailed: "প্রোফাইল আপডেট করতে ব্যর্থ হয়েছে",
        // Donor Registration Dialog
        donorRegistration: "রক্তদাতা নিবন্ধন",
        personalInfo: "ব্যক্তিগত তথ্য",
        healthScreening: "স্বাস্থ্য পরীক্ষা",
        termsPrivacy: "শর্তাবলী ও গোপনীয়তা",
        basicDetails: "মৌলিক তথ্য",
        medicalHistory: "চিকিৎসার ইতিহাস",
        legalAgreement: "আইনি চুক্তি",
        personalInfoDesc: "আপনার ব্যক্তিগত তথ্য এবং যোগাযোগের বিবরণ প্রদান করুন",
        healthScreeningDesc: "স্বাস্থ্য সচেতনতা সম্পর্কিত প্রশ্নাবলী সম্পন্ন করুন (শুধুমাত্র রক্তদাতাদের জন্য)",
        termsPrivacyDesc: "আমাদের সেবার শর্তাবলী এবং গোপনীয়তা নীতি পর্যালোচনা করুন এবং গ্রহণ করুন",
        healthScreeningRequired: "স্বাস্থ্য পরীক্ষা আবশ্যক",
        healthScreeningNote: "অনুগ্রহ করে সকল প্রশ্নের সত্য উত্তর দিন। এই তথ্য রক্তদাতা এবং গ্রহীতা উভয়ের জন্য নিরাপদ রক্তদান নিশ্চিত করতে সহায়তা করে।",
        weightPlaceholder: "ওজন নির্বাচন করুন",
        heightPlaceholder: "১৭০",
        minWeightNote: "নূনতম ৫০ কেজি প্রয়োজন",
        lastDonationDate: "সর্বশেষ রক্তদানের তারিখ",
        dateOfBirth: "জন্ম তারিখ",
        firstTimeDonor: "প্রথম বার?",
        mustBe18to60: "১৮-৬০ বছর বয়সী হতে হবে",
        otherMedicalConditions: "অন্যান্য শারীরিক অবস্থা",
        lifestyleMedications: "জীবনধারা ও ওষুধ",
        recentActivities: "সাম্প্রতিক কার্যক্রম",
        recentActivitiesNote: "গত ৩ মাসের মধ্যে আপনি কি:",
        medicalHistoryNote: "আপনি কি বর্তমানে নিচের কোনো শারীরিক সমস্যায় ভুগছেন বা অতীতে কখনো আপনার এই সমস্যাগুলো ধরা পড়েছে?",
        otherConditionsPlaceholder: "দয়া করে অন্য কোনো সমস্যা থাকলে উল্লেখ করুন",
        confirmAccuracy: "আমি নিশ্চিত করছি যে উপরে প্রদান করা সমস্ত তথ্য সঠিক এবং সম্পূর্ণ",
        termsOfServiceAgree: "আমি সেবার শর্তাবলীতে সম্মত",
        privacyPolicyAgree: "আমি গোপনীয়তা নীতিতে সম্মত",
        notificationConsent: "আমি জরুরি রক্তের অনুরোধ সম্পর্কে এসএমএস এবং ইমেইল বিজ্ঞপ্তি পেতে সম্মত",
        notificationConsentNote: "আপনি পরে আপনার প্রোফাইল সেটিংসে এই পছন্দটি পরিবর্তন করতে পারেন",
        profileSharingConsent: "আমি রক্তের গ্রুপ মিললে যাচাইকৃত গ্রহীতাদের সাথে আমার প্রোফাইল তথ্য শেয়ার করতে সম্মত",
        profileSharingConsentNote: "প্লাটফর্মের কার্যকারিতা এবং রক্তদাতাদের গ্রহীতাদের সাথে সংযুক্ত করার জন্য এটি অপরিহার্য",
        privacyMatters: "আপনার গোপনীয়তা আমাদের কাছে গুরুত্বপূর্ণ",
        weight: "ওজন",
        height: "উচ্চতা (সেমি)",
        previous: "আগের",
        next: "পরবর্তী",
        privacyMattersNote: "আমরা আপনার ব্যক্তিগত তথ্য এবং চিকিৎসা সংক্রান্ত তথ্য সুরক্ষায় প্রতিশ্রুতিবদ্ধ। আপনার তথ্য এনক্রিপ্ট করা থাকে এবং শুধুমাত্র রক্তদানের উদ্দেশ্যে আপনার স্পষ্ট সম্মতিতে শেয়ার করা হয়।",
        secureRegistration: "নিরাপদ নিবন্ধন",
        registering: "নিবন্ধন হচ্ছে...",
        completeRegistration: "নিবন্ধন সম্পন্ন করুন",
        registrationSuccess: "নিবন্ধন সফল হয়েছে!",
        registrationSuccessNote: "রক্তদাতা হওয়ার জন্য আপনাকে ধন্যবাদ। আপনার প্রতিশ্রুতি জীবন বাঁচাতে সাহায্য করে।",
        done: "সম্পন্ন",
        missingInfo: "তথ্য অনুপস্থিত",
        fillRequiredFields: "অনুগ্রহ করে * চিহ্নিত সমস্ত আবশ্যক ক্ষেত্র পূরণ করুন",
        invalidEmail: "অকার্যকর ইমেইল",
        enterValidEmail: "অনুগ্রহ করে একটি সঠিক ইমেইল ঠিকানা লিখুন",
        invalidPhone: "অকার্যকর ফোন নম্বর",
        enterValidPhone: "অনুগ্রহ করে একটি সঠিক বাংলাদেশী ফোন নম্বর লিখুন",
        enterWeightHeight: "অনুগ্রহ করে আপনার ওজন এবং উচ্চতা লিখুন",
        provideLastDonationDate: "অনুগ্রহ করে আপনার সর্বশেষ রক্তদানের তারিখ প্রদান করুন অথবা আপনি প্রথমবার রক্তদাতা কিনা তা জানান",
        confirmationRequired: "নিশ্চিতকরণ প্রয়োজন",
        confirmInfoAccurate: "অনুগ্রহ করে নিশ্চিত করুন যে প্রদান করা তথ্য সঠিক",
        agreementsRequired: "চুক্তি আবশ্যক",
        acceptAgreements: "অনুগ্রহ করে সেবার শর্তাবলী, গোপনীয়তা নীতি এবং প্রোফাইল শেয়ারিং সম্মতিতে স্বাক্ষর করুন",
        registrationFailed: "নিবন্ধন ব্যর্থ হয়েছে",
        division: "বিভাগ",
        divisionPlaceholder: "আপনার বিভাগ নির্বাচন করুন",
        fullAddress: "সম্পূর্ণ ঠিকানা",
        fullAddressPlaceholder: "বাসা/রাস্তা/এলাকার বিবরণ",
        recipientsFindYou: "এটি আপনার কাছের গ্রহীতাদের আপনাকে খুঁজে পেতে সাহায্য করে",
        activePhoneNote: "নোট: দয়া করে নিশ্চিত করুন যে এটি আপনার সক্রিয় ফোন নম্বর।",
        // Medical conditions
        heartDisease: "হৃদরোগ বা হার্টের সমস্যা",
        diabetes: "ডায়াবেটিস",
        hepatitis: "হেপাটাইটিস বি বা সি",
        tuberculosis: "যক্ষ্মা",
        liverDisease: "লিভারের রোগ",
        highLowBloodPressure: "উচ্চ বা নিম্ন রক্তচাপ",
        cancerBloodDisorders: "ক্যান্সার বা রক্তের ব্যাধি",
        hivAids: "এইচআইভি/এইডস",
        kidneyDisease: "কিডনি রোগ",
        epilepsySeizures: "মৃগীরোগ বা খিঁচুনি",
        // Lifestyle
        prescriptionMedications: "আমি বর্তমানে প্রেসক্রিপশন অনুযায়ী ওষুধ খাচ্ছি",
        smokeTobacco: "আমি তামাকজাত পণ্য ধূমপান করি",
        consumeAlcohol: "আমি নিয়মিত অ্যালকোহল সেবন করি",
        // Recent activities
        vaccinations: "কোনো টিকাদান বা ইমিউনাইজেশন করিয়েছেন",
        dentalWork: "কোনো দাঁতের কাজ বা সার্জারি করিয়েছেন",
        traveledOutside: "বাংলাদেশের বাইরে ভ্রমণ করেছেন",
        tattoosPiercings: "কোনো ট্যাটু বা পিয়ার্সিং করিয়েছেন",
        beenSick: "জ্বর, সর্দি বা ফ্লুতে অসুস্থ হয়েছেন",
        // Other Registration Details

        watchDemo: "৬০ সেকেন্ডের ডেমো দেখুন",
        getStarted: "শুরু করুন",
        platformAvailability: "প্ল্যাটফর্মের প্রাপ্যতা",
        noHiddenCharges: "কখনো কোনো লুকানো চার্জ নেই",
        step1Title: "নিবন্ধন করুন",
        step1Desc: "বেসিক তথ্য এবং ফোন যাচাইকরণের মাধ্যমে ৩০ সেকেন্ডে আপনার অ্যাকাউন্ট তৈরি করুন।",
        step2Title: "খুঁজুন বা অনুরোধ করুন",
        step2Desc: "কাছের উপযুক্ত রক্তদাতাদের খুঁজুন অথবা তাৎক্ষণিকভাবে জরুরি রক্তের অনুরোধ পোস্ট করুন।",
        step3Title: "দাতার সাথে যোগাযোগ করুন",
        step3Desc: "কল বা হোয়াটসঅ্যাপের মাধ্যমে সরাসরি যাচাইকৃত দাতাদের সাথে যোগাযোগ করুন। দ্রুত এবং নিরাপদ।",
        step4Title: "জীবন বাঁচান",
        step4Desc: "রক্তদান সম্পন্ন করুন এবং আপনার জীবন রক্ষাকারী অবদানের জন্য ব্যাজ অর্জন করুন।",
        // Testimonials
        realStories: "বাস্তব গল্প",
        communitySays: "আমাদের সম্প্রদায় যা বলছে",
        testimonialsDesc: "যাচাইকৃত রক্তদাতা এবং গ্রহীতাদের বাস্তব গল্প যারা সম্প্রদায়ের শক্তির অভিজ্ঞতা অর্জন করেছেন",
        verifiedDonorBadge: "যাচাইকৃত রক্তদাতা",
        verifiedPatientBadge: "যাচাইকৃত রোগী",
        testimonial1Name: "রহিম আহমেদ",
        testimonial1Role: "নিয়মিত রক্তদাতা",
        testimonial1Quote: "ব্লাডকানেক্টের মাধ্যমে রক্তদান করা অবিশ্বাস্যভাবে সহজ। আমি একাধিক জীবন বাঁচিয়েছি এবং এটি দারুণ অনুভূতি!",
        testimonial2Name: "ফাতিমা বেগম",
        testimonial2Role: "জরুরি রক্ত গ্রহীতা",
        testimonial2Quote: "যখন আমার বাবার জরুরি রক্তের প্রয়োজন ছিল, ব্লাডকানেক্ট কয়েক ঘণ্টার মধ্যে আমাদের রক্তদাতাদের সাথে সংযুক্ত করেছিল!",
        testimonial3Name: "করিম হাসান",
        testimonial3Role: "মাসিক রক্তদাতা",
        testimonial3Quote: "প্রক্রিয়াটি নিরবচ্ছিন্ন এবং সম্প্রদায়টি চমৎকার। এই জীবন রক্ষাকারী নেটওয়ার্কের অংশ হতে পেরে আমি গর্বিত।",
        testimonial4Name: "আয়েশা রহমান",
        testimonial4Role: "মা ও গ্রহীতা",
        testimonial4Quote: "আমার সন্তানের জরুরি রক্তের প্রয়োজন ছিল। এখানকার চমৎকার দাতাদের ধন্যবাদ, সে এখন সুস্থ।",
        testimonial5Name: "ইমরান হোসেন",
        testimonial5Role: "প্রথমবার রক্তদাতা",
        testimonial5Quote: "প্রথমবার রক্তদান করে আমি বুঝতে পেরেছি যে কারো জীবনে সত্যিকারের পরিবর্তন আনা কতটা সহজ।",
        testimonial6Name: "নাসরিন আক্তার",
        testimonial6Role: "সম্প্রদায় সংগঠক",
        testimonial6Quote: "ব্লাডকানেক্টের সাথে আমাদের সম্প্রদায়ের কর্মসূচি ঐক্য ও দয়া বৃদ্ধি করে। একসাথে জীবন বাঁচানো চমৎকার!",
        // Find Donors Page
        findBloodDonors: "রক্তদাতা খুঁজুন",
        connectVerifiedDonors: "আপনার এলাকার যাচাইকৃত রক্তদাতাদের সাথে যোগাযোগ করুন",
        filters: "ফিল্টার",
        resetAllFilters: "সব ফিল্টার রিসেট করুন",
        bloodGroup: "রক্তের গ্রুপ",
        selectBloodGroup: "রক্তের গ্রুপ নির্বাচন করুন",
        location: "অবস্থান",
        enterAreaDistrict: "এলাকা/জেলা লিখুন",
        gender: "লিঙ্গ",
        selectGender: "লিঙ্গ নির্বাচন করুন",
        any: "যেকোনো",
        lastDonation: "সর্বশেষ রক্তদান",
        selectPeriod: "সময়কাল নির্বাচন করুন",
        availability: "প্রাপ্যতা",
        selectAvailability: "প্রাপ্যতা নির্বাচন করুন",
        distance: "দূরত্ব",
        distanceLabel: "দূরত্ব",
        selectDistance: "দূরত্ব নির্বাচন করুন",
        urgentAvailability: "জরুরি প্রাপ্যতা",
        verifiedDonorsFilter: "যাচাইকৃত রক্তদাতা",
        searchDonorsPlaceholder: "নাম বা অবস্থান দিয়ে রক্তদাতা খুঁজুন...",
        showingDonors: "{count} জন রক্তদাতা দেখানো হচ্ছে",
        sortByDistance: "দূরত্ব অনুযায়ী সাজান",
        sortByRating: "রেটিং অনুযায়ী সাজান",
        sortByDonations: "রক্তদান অনুযায়ী সাজান",
        sortByRecent: "সাম্প্রতিক কার্যক্রম অনুযায়ী সাজান",
        loadingDonors: "রক্তদাতা খোঁজা হচ্ছে...",
        failedToLoadDonors: "রক্তদাতা লোড করতে ব্যর্থ হয়েছে:",
        noDonorsFound: "কোনো রক্তদাতা পাওয়া যায়নি।",
        notAvailable: "পাওয়া যাবে না",
        lastDonationPrefix: "সর্বশেষ রক্তদান: ",
        noRecentDonation: "সাম্প্রতিক রক্তদানের তথ্য নেই",
        viewProfile: "প্রোফাইল দেখুন",
        loadMoreDonors: "আরও রক্তদাতা দেখুন",
        active: "সক্রিয়",
        anonymousDonor: "নামহীন রক্তদাতা",
        // First Visit Banner
        welcomeToBloodConnect: "ব্লাডকানেক্ট-এ স্বাগতম!",
        register30Sec: "৩০ সেকেন্ডে নিবন্ধন করুন। আজই একটি জীবন বাঁচান।",
        signup30Sec: "৩০ সেকেন্ডের সাইনআপ",
        joinNow: "এখনই যোগ দিন",
        join: "যোগ দিন",
        // Exit Intent Popup
        dontLeaveYet: "এখনই যাবেন না",
        beforeYouLeave: "যাওয়ার আগে —",
        someoneNearYou: "আপনার কাছের কারো রক্তের প্রয়োজন হতে পারে।",
        every2Seconds: "প্রতি ২ সেকেন্ডে",
        bdEvery2Seconds: "বাংলাদেশে কারো না কারো রক্ত প্রয়োজন। আপনার আজই একটি জীবন বাঁচাতে পারে।",
        registerAsDonor: "রক্তদাতা হিসেবে নিবন্ধন করুন",
        maybeLater: "পরে হবে",
        // Generic Actions
        postRequest: "অনুরোধ পোস্ট করুন",
        // Trust & Security
        trustSecurity: "বিশ্বাস ও নিরাপত্তা",
        safetyPriority: "আপনার নিরাপত্তা আমাদের অগ্রাধিকার",
        trustDesc: "আমাদের প্ল্যাটফর্মে প্রতিটি লেনদেন নিরাপদ এবং আসল তা নিশ্চিত করতে আমরা ভেরিফিকেশনের একাধিক স্তর ব্যবহার করি",
        phoneVerified: "ফোন-যাচাইকৃত রক্তদাতা",
        phoneVerifiedDesc: "প্রতিটি রক্তদাতার ফোন নম্বর ওটিপি-র মাধ্যমে যাচাই করা হয়",
        fakeRequestsBanned: "ভুয়া অনুরোধ নিষিদ্ধ",
        fakeRequestsBannedDesc: "প্রতারণামূলক অ্যাকাউন্টগুলো স্থায়ীভাবে নিষিদ্ধ করা হয়",
        hospitalVerified: "হাসপাতাল যাচাইকৃত",
        hospitalVerifiedDesc: "অংশীদার হাসপাতালগুলোর মাধ্যমে অনুরোধের অবস্থান যাচাই করা হয়",
        dataEncrypted: "তথ্য এনক্রিপ্টেড",
        dataEncryptedDesc: "সব ব্যক্তিগত ডেটা এনক্রিপ্ট এবং সুরক্ষিত রাখা হয়",
        trustedByCount: "সারা বাংলাদেশে ৫০,০০০+ যাচাইকৃত রক্তদাতা দ্বারা বিশ্বস্ত",
        // Trusted Partners
        trustedPartners: "শীর্ষস্থানীয় অংশীদারদের দ্বারা বিশ্বস্ত",
        trustedPartnersDesc: "আমরা জীবন বাঁচাতে শীর্ষস্থানীয় সংস্থাগুলোর সাথে সহযোগিতা করি",
        // Urgent Requests
        urgentBloodRequests: "জরুরি রক্তের অনুরোধ",
        fetchingRequests: "সর্বশেষ জরুরি রক্তের অনুরোধগুলো খুঁজছি...",
        troubleLoading: "অনুরোধগুলো লোড করতে সমস্যা হচ্ছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
        retry: "আবার চেষ্টা করুন",
        allClear: "সব ঠিক আছে",
        noUrgentRequests: "বর্তমানে কোনো জরুরি অনুরোধ নেই",
        noUrgentRequestsDesc: "সুসংবাদ! এই মুহূর্তে কোনো জরুরি রক্তের অনুরোধ নেই। পরে আবার দেখুন অথবা সব অনুরোধ ব্রাউজ করুন।",
        viewAllRequests: "সব অনুরোধ দেখুন",
        liveEmergencyRequests: "লাইভ জরুরি অনুরোধ",
        urgentRequestsDesc: "এই রোগীদের অবিলম্বে রক্তদান প্রয়োজন। আপনার দ্রুত সাড়া একটি জীবন বাঁচাতে পারে।",
        bloodNeeded: "রক্ত প্রয়োজন",
        unitsRequired: "ইউনিট প্রয়োজন",
        posted: "পোস্ট করা হয়েছে",
        callNow: "কল করুন",
        minAgo: "মিনিট আগে",
        hAgo: "ঘণ্টা আগে",
        dAgo: "দিন আগে",
        // Time Ago with variables
        secondsAgo: "{count} সেকেন্ড আগে",
        minutesAgo: "{count} মিনিট আগে",
        hoursAgo: "{count} ঘণ্টা আগে",
        daysAgo: "{count} দিন আগে",
        // Blood Request Feed & Cards
        patient: "রোগী",
        contactPerson: "যোগাযোগকারী ব্যক্তি",
        unitsNeeded: "{units} ইউনিট প্রয়োজন",
        share: "শেয়ার করুন",
        iCanHelp: "আমি সাহায্য করতে পারি",
        noRequestsFound: "কোনো রক্তের অনুরোধ পাওয়া যায়নি।",
        noMatchFound: "\"{query}\"-এর সাথে মিল থাকা কোনো রক্তের অনুরোধ পাওয়া যায়নি",
        loadingRequests: "রক্তের অনুরোধ লোড হচ্ছে...",
        messageSent: "বার্তা পাঠানো হয়েছে!",
        messageSentDesc: "আমাদের সাথে যোগাযোগ করার জন্য ধন্যবাদ। আমরা শীঘ্রই আপনার সাথে যোগাযোগ করব।",
        // Footer & Generic
        needBloodUrgently: "জরুরি রক্ত প্রয়োজন?",
        postEmergencyRequest: "জরুরি রক্ত অনুরোধ পোস্ট করুন",
        whatsApp: "হোয়াটসঅ্যাপ",
        footerMission: "বাংলাদেশের নির্ভরযোগ্য রক্তদান প্ল্যাটফর্ম। যাচাইকৃত রক্তদাতাদের রোগীদের সাথে ২৪/৭ সংযুক্ত করা।",
        partnerHospitalsTitle: "পার্টনার হাসপাতাল",
        morePartners: "+ আরও ৫০টি পার্টনার",
        hotline: "হটলাইন",
        support247: "২৪/৭ সাপোর্ট",
        privacyPolicy: "গোপনীয়তা নীতি",
        termsOfService: "পরিষেবার শর্তাবলী",
        madeWith: "তৈরি করা হয়েছে",
        forBangladesh: "বাংলাদেশের জন্য",
        allRightsReserved: "সর্বস্বত্ব সংরক্ষিত।",
        links: "দ্রুত লিঙ্ক",
        newsletter: "নিউজলেটারে যুক্ত হোন",
        subscribe: "সাবস্ক্রাইব",

        // About Page
        aboutTitle: "ব্লাডকানেক্ট সম্পর্কে",
        aboutMission: "ব্লাডকানেক্ট হল একটি প্ল্যাটফর্ম যা বাংলাদেশজুড়ে রক্তদাতা এবং গ্রহীতাদের সংযোগ করার জন্য নিবেদিত। আমাদের লক্ষ্য হল রক্তদাতা খুঁজে পাওয়ার সময় কমানো, জরুরি অনুরোধগুলো ত্বরান্বিত করা এবং একটি নির্ভরযোগ্য, সম্প্রদায়-চালিত নেটওয়ার্ক তৈরি করা যা প্রতিদিন প্রাণ বাঁচায়।",
        whatWeDo: "আমরা কী করি",
        whatWeDoDesc: "আমরা রক্তদাতার প্রাপ্যতা একত্রিত করি, জরুরি অনুরোধগুলো মেলাই এবং রিয়েল-টাইমে সম্ভাব্য রক্তদাতাদের অবহিত করি।",
        whyItMatters: "কেন এটি গুরুত্বপূর্ণ",
        whyItMattersDesc: "সময়মতো রক্ত পাওয়া জীবন রক্ষাকারী হতে পারে। আমরা ঘর্ষণ, বিলম্ব এবং অনিশ্চয়তা কমাতে সাহায্য করি।",
        forOurUsers: "আমাদের ব্যবহারকারীদের জন্য",
        forOurUsersDesc: "রক্তদাতারা অবদান রাখার একটি সহজ উপায় পান। গ্রহীতারা জরুরি সাহায্যের জন্য একটি নির্ভরযোগ্য পথ পান।",
        privacyPolicyTitle: "গোপনীয়তা নীতি",
        privacyPolicyDesc: "আমরা প্ল্যাটফর্ম পরিচালনার জন্য প্রয়োজনীয় তথ্য সংগ্রহ করি—যেমন অ্যাকাউন্টের বিবরণ এবং রক্তদাতার পছন্দ। আপনার ডেটা নিরাপদে সংরক্ষণ করা হয় এবং শুধুমাত্র পরিষেবার কার্যকারিতা, নিরাপত্তা এবং সম্মতির জন্য অ্যাক্সেস করা হয়। আমরা আপনার ব্যক্তিগত তথ্য কখনও বিক্রি করি না। আপনি প্রযোজ্য আইন অনুযায়ী ডেটা এক্সপোর্ট বা মুছে ফেলার অনুরোধ করতে পারেন।",
        faqTitle: "সচরাচর জিজ্ঞাসিত প্রশ্নাবলী",
        faqQ1: "আমি কীভাবে রক্তদাতা হব?",
        faqA1: "একটি অ্যাকাউন্ট তৈরি করুন এবং আপনার রক্তের গ্রুপ এবং প্রাপ্যতা সহ রক্তদাতার প্রোফাইলটি সম্পূর্ণ করুন। আপনি যে কোনো সময় পছন্দগুলো আপডেট করতে পারেন।",
        faqQ2: "আমার ব্যক্তিগত তথ্য কি নিরাপদ?",
        faqA2: "হ্যাঁ। আমরা সুরক্ষিত স্টোরেজ ব্যবহার করি এবং অপারেশনাল প্রয়োজনে অ্যাক্সেস সীমিত করি। বিস্তারিত জানার জন্য আমাদের গোপনীয়তা নীতি দেখুন।",
        faqQ3: "আপনারা কি কোনো ফি নেন?",
        faqA3: "না। ব্লাডকানেক্ট রক্তদাতা এবং গ্রহীতাদের জন্য সম্পূর্ণ বিনামূল্যে। আমরা ভবিষ্যতে স্পষ্ট প্রকাশের সাথে ঐচ্ছিক বৈশিষ্ট্য যোগ করতে পারি।",
        faqQ4: "কীভাবে ম্যাচ বা মিল করা হয়?",
        faqA4: "আমরা রক্তের গ্রুপের সামঞ্জস্য, নিকটতা এবং রক্তদাতার প্রাপ্যতার ভিত্তিতে সার্চ করি যাতে দ্রুত সাড়া এবং নিরাপত্তা নিশ্চিত করা যায়।",

        // Contact Page
        contactTitle: "যোগাযোগ করুন",
        contactSubtitle: "আপনার কি কোনো প্রশ্ন আছে বা সাহায্যের প্রয়োজন? আমরা আপনাকে প্রাণ বাঁচাতে সাহায্য করতে এখানে আছি। যে কোনো সময় আমাদের সাথে যোগাযোগ করুন।",
        emergencyHotline: "জরুরি হটলাইন",
        hotlineHours: "জরুরি রক্তের প্রয়োজনে ২৪/৭ উপলব্ধ",
        emailUs: "আমাদের ইমেইল করুন",
        emailResponse: "আমরা ২৪ ঘণ্টার মধ্যে উত্তর দেব",
        headOffice: "প্রধান কার্যালয়",
        headOfficeLocation: "ঢাকা, বাংলাদেশ",
        officeHours: "অফিস সময়",
        officeHoursDesc: "রবি - বৃহস্পতি: সকাল ৯টা - সন্ধ্যা ৬টা",
        officeHoursClosed: "সরকারি ছুটির দিনে বন্ধ",
        telephoneEnquiries: "রক্তদাতা টেলিফোন অনুসন্ধান",
        hotlineNumber: "০৩৪৫ ৯০ ৯০ ৯৯৯",
        monFri: "সোমবার - শুক্রবার: সকাল ৯:০০ - বিকাল ৫:০০",
        callUsIfTitle: "আমাদের ফোন করুন যদি আপনি:",
        ringSignUps: "রক্তদাতা হিসেবে সাইন আপ করতে চান",
        ringSignUpsDesc: "জীবন রক্ষাকারী রক্তদাতা হতে নিবন্ধন করুন",
        ringQuestions: "রক্তদান সম্পর্কে প্রশ্ন থাকে",
        ringQuestionsDesc: "আপনার রক্তদান সংক্রান্ত প্রশ্নের উত্তর পান",
        ringAppointment: "অ্যাপয়েন্টমেন্ট নিন বা বাতিল করুন",
        ringAppointmentDesc: "অধিবেশনের আগের দিন বিকাল ৫টা পর্যন্ত",
        ringMedical: "চিকিৎসা পরামর্শ প্রয়োজন",
        ringMedicalDesc: "আমাদের মেডিকেল টিমের সাথে পরামর্শ করুন",
        ringUnwell: "রক্তদানের পর অসুস্থ বোধ করেন",
        ringUnwellDesc: "মেডিকেল টিম ২৪ ঘণ্টা অন-কলে থাকে",
        ringDiscomfort: "রক্তদানের পর অস্বস্তি অনুভব করেন",
        ringDiscomfortDesc: "মেডিকেল টিম ২৪ ঘণ্টা অন-কলে থাকে",
        ringUsage: "রক্তের ব্যবহার সম্পর্কে সন্দেহ থাকলে",
        ringUsageDesc: "রক্তদানের পর উদ্বেগ",
        importantNote: "নোট:",
        medicalEmergencyNote: "রক্তদানের পর চিকিৎসা সংক্রান্ত জরুরি অবস্থার জন্য, আমাদের মেডিকেল টিম ২৪/৭ উপলব্ধ। আপনি যদি কোনো অস্বস্তি বা উদ্বেগের সম্মুখীন হন তবে কল করতে দ্বিধা করবেন না।",
        sendMessage: "আমাদের একটি বার্তা পাঠান",
        sendMessageDesc: "নিচের ফর্মটি পূরণ করুন এবং আমরা যত দ্রুত সম্ভব আপনার সাথে যোগাযোগ করব।",
        fullContactName: "পুরো নাম *",
        enterFullName: "আপনার পুরো নাম লিখুন",
        emailAddressLabel: "ইমেইল ঠিকানা *",
        phoneOptional: "ফোন নম্বর (ঐচ্ছিক)",
        subjectLabel: "বিষয় *",
        regardingSubject: "এটি কী সম্পর্কিত?",
        messageLabel: "বার্তা *",
        tellMoreMessage: "আপনার অনুসন্ধান সম্পর্কে আমাদের আরও বলুন...",
        characters: "অক্ষর",
        sendingMessage: "বার্তা পাঠানো হচ্ছে...",
        responseTimeNote: "উত্তরের সময়:",
        typicallyRespond: "আমরা সাধারণত কর্মদিবসে ২৪ ঘণ্টার মধ্যে সমস্ত অনুসন্ধানের উত্তর দেই।",
        needSomethingElse: "অন্য কিছু প্রয়োজন?",
        quickAccessFeatures: "আমাদের সবচেয়ে জনপ্রিয় বৈশিষ্ট্যগুলোতে দ্রুত এক্সেস",
        invalidName: "নাম অন্তত ২ অক্ষরের হতে হবে",
        invalidSubject: "বিষয় অন্তত ৫ অক্ষরের হতে হবে",
        invalidMessage: "বার্তা অন্তত ১০ অক্ষরের হতে হবে",
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem("language");
        return (saved as Language) || "en";
    });

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("language", lang);
    };

    const t = (key: string, variables?: Record<string, any>) => {
        let translation = translations[language][key as keyof typeof translations['en']] || key;

        if (variables) {
            Object.entries(variables).forEach(([vKey, vValue]) => {
                translation = translation.replace(`{${vKey}}`, String(vValue));
            });
        }

        return translation;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
};
